name: Auto Create Branch

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate labels
        id: check_labels
        run: |
          if [ -z "${{ github.event.issue.labels.*.name }}" ]; then
            echo "error=No labels assigned" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Set branch prefix
        id: set_prefix
        run: |
          case "${{ github.event.issue.labels.*.name }}" in
            *"feat"*)   echo "prefix=feature" >> $GITHUB_OUTPUT ;;
            *"bug"*)    echo "prefix=bugfix" >> $GITHUB_OUTPUT ;;
            *"hotfix"*) echo "prefix=hotfix" >> $GITHUB_OUTPUT ;;
            *"refactor"*) echo "prefix=refactor" >> $GITHUB_OUTPUT ;;
            *)          echo "prefix=task" >> $GITHUB_OUTPUT ;;
          esac

      - name: Sanitize branch name
        id: sanitize
        run: |
          CLEAN_TITLE=$(echo "${{ github.event.issue.title }}" | iconv -f utf-8 -t ascii//TRANSLIT | tr -cd '[:alnum:]-_' | cut -c 1-63)
          echo "name=$CLEAN_TITLE" >> $GITHUB_OUTPUT

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.set_prefix.outputs.prefix }}/#${{ github.event.issue.number }}-${{ steps.sanitize.outputs.name }}

      - name: Link branch to issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: `자동 생성 브랜치: \`${{ steps.set_prefix.outputs.prefix }}/#${{ github.event.issue.number }}-${{ steps.sanitize.outputs.name }}\``
            })
