name: Auto Create Branch

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  create-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch prefix
        id: set_prefix
        run: |
          case "${{ join(github.event.issue.labels.*.name, ',') }}" in
            *"feat"*)   echo "prefix=feature" >> $GITHUB_OUTPUT ;;
            *"bug"*)    echo "prefix=bugfix" >> $GITHUB_OUTPUT ;;
            *"hotfix"*) echo "prefix=hotfix" >> $GITHUB_OUTPUT ;;
            *"refactor"*) echo "prefix=refactor" >> $GITHUB_OUTPUT ;;
            *)          echo "prefix=task" >> $GITHUB_OUTPUT ;;
          esac

      - name: Sanitize branch name
        id: sanitize
        run: |
          CLEAN_TITLE=$(echo "${{ github.event.issue.title }}" | 
            iconv -f utf-8 -t ascii//TRANSLIT//IGNORE |
            tr -cd '[:alnum:]-_' |
            tr '[:upper:]' '[:lower:]' |
            cut -c 1-63)
          echo "name=${CLEAN_TITLE}" >> $GITHUB_OUTPUT

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.set_prefix.outputs.prefix }}/#${{ github.event.issue.number }}-${{ steps.sanitize.outputs.name }}
